apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: ${resourceName}-cluster-apps
  namespace: ${templateNamespace}
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: global-config
        files:
          - path: resource-descriptions/${templateNamespace}/${resourceName}.yaml
  templates:
    - repeat: '{ .clusters[?(@.name=="${clusterName}")].apps }'
      content:
        kind: Kustomization
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        metadata:
          name: ${resourceName}-app-{{ .Repeat.name }}
          annotations:
            templates.weave.works/create-request: ''
        spec:
          interval: 10m0s
          sourceRef:
            kind: GitRepository
            name: global-config
            namespace: flux-system
          path: ./leaf-clusters/apps/templates/oci-app
          prune: true
          wait: true
          timeout: 5m
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-config
            substitute:
              appName: '{{ .Repeat.name }}'

