---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-config
  namespace: dex
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dex-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dex-config

