# Create ECR repository and any other AWS resources required for Flux application deployment to cluster
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: onboarding-clusters
  namespace: flux-apps
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: clusters
        directories:
          - path: resource-descriptions/clusters/*
  templates:
    content:
      kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      metadata:
        name: ecr-repo-cluster-{{ trimSuffix ".yaml" .Element.Base }}
        namespace: flux-apps
        annotations:
          templates.weave.works/create-request: ''
      spec:
        interval: 10m0s
        sourceRef:
          kind: GitRepository
          name: global-config
          namespace: flux-system
        path: ./infra/dynamic/ecr-repo
        prune: true
        wait: true
        timeout: 5m
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-config
          substitute:
            ecrName: 'cluster-{{ trimSuffix ".yaml" .Element.Base }}'
            templateNamespace: flux-apps
            resourceName: test1
---
kind: Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
metadata:
  name: ecr-repo-templates
  namespace: flux-apps
annotations:
  templates.weave.works/create-request: ''
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  path: ./infra/dynamic/ecr-repo
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
    substitute:
      ecrName: templates
      templateNamespace: flux-apps
      resourceName: test1
---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: onboarding-namespaces
  namespace: flux-apps
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: clusters
        directories:
          - path: resource-descriptions/namespaces/*
  templates:
    content:
      apiVersion: templates.weave.works/v1alpha1
      kind: GitOpsSet
      metadata:
        annotations:
          templates.weave.works/delimiters: "((,))"
        labels:
          app.kubernetes.io/name: gitopsset
          app.kubernetes.io/instance: gitopsset-sample
          app.kubernetes.io/part-of: gitopssets-controller
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/created-by: gitopssets-controller
        name: flux-appsonboarding-ns-{{ trimSuffix ".yaml" .Element.Base }}-apps
        namespace: flux-apps
      spec:
        serviceAccountName: gitopssets
        generators:
          - gitRepository:
              repositoryRef: clusters
              files:
                - path: resource-descriptions/namespaces/{{ .Element.Base }}
        templates:
          - repeat: '{ .apps }'
            content:
              kind: Kustomization
              apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
              metadata:
                name: ecr-repo-ns-{{ trimSuffix ".yaml" .Element.Base }}-app-(( .Repeat.name ))-manifest
                annotations:
                  templates.weave.works/create-request: ''
              spec:
                interval: 10m0s
                sourceRef:
                  kind: GitRepository
                  name: global-config
                  namespace: flux-system
                path: ./infra/dynamic/ecr-repo
                prune: true
                wait: true
                timeout: 5m
                postBuild:
                  substituteFrom:
                    - kind: ConfigMap
                      name: cluster-config
                  substitute:
                    ecrName: 'ns-{{ trimSuffix ".yaml" .Element.Base }}-app-(( .Repeat.name ))-manifest'
                    templateNamespace: flux-apps
                    resourceName: test1
          - repeat: '{ .apps }'
            content:
              kind: Kustomization
              apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
              metadata:
                name: ecr-repo-ns-{{ trimSuffix ".yaml" .Element.Base }}-app-(( .Repeat.name ))-config
                annotations:
                  templates.weave.works/create-request: ''
              spec:
                interval: 10m0s
                sourceRef:
                  kind: GitRepository
                  name: global-config
                  namespace: flux-system
                path: ./infra/dynamic/ecr-repo
                prune: true
                wait: true
                timeout: 5m
                postBuild:
                  substituteFrom:
                    - kind: ConfigMap
                      name: cluster-config
                  substitute:
                    ecrName: 'ns-{{ trimSuffix ".yaml" .Element.Base }}-app-(( .Repeat.name ))-config'
                    templateNamespace: flux-apps
                    resourceName: 
