apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${resourceName}-cluster-apps
  namespace: ${templateNamespace}
spec:
  prune: true
  wait: true
  timeout: 5m
  interval: 5m
  sourceRef:
    kind: OCIRepository
    name: ${resourceName}-cluster-apps
  path: ./
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
