---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: aws-s3-bucket
  namespace: flux-system
spec:
  path: terraform/remote-state
  sourceRef:
    kind: GitRepository
    name: global-config
  approvePlan: auto
  retryInterval: 1m
  interval: 1h
  destroyResourcesOnDeletion: true
  writeOutputsToSecret:
    name: aws-s3-bucket-outputs
    outputs:
    - arn
    - bucket
  vars:
    - name: bucket_name
      value: ${prefixName}-${awsAccountId}-${awsRegion}-tf-state
    - name: tags
      value:
        creator: ${awsTagCreator}
        customer: ${awsTagCustomer}
        projectGid: ${awsTagProjectGid}
  varsFrom:
    - kind: ConfigMap
      name: cluster-config
      varsKeys:
        - awsAccountId
        - awsRegion
    - kind: Secret
      name: aws-s3-bucket-outputs
      optional: true
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-creds
  