apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: clusters
  namespace: ${templateNamespace}
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/${GitHubOrg}/clusters.git
