apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${resourceName}-s3-bootstrap
  namespace: ${templateNamespace}
spec:
  prune: true
  wait: true
  timeout: 5m
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: clusters
  path: ./cluster-yamls/s3-src
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
