apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: clusters
  namespace: ${templateNamespace}
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/${GitHubOrg}/clusters.git
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ${resourceName}-cluster-apps
  namespace: ${templateNamespace}
spec:
  provider: aws
  interval: 10m
  url: oci://${awsAccountId}.dkr.ecr.${awsRegion}.amazonaws.com/cluster-${clusterName}
  ref:
    tag: v0.0.2
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: ${resourceName}-cluster-apps
  namespace: ${templateNamespace}
  # labels:
  #   sharding.fluxcd.io/key: $shard
spec:
  type: generic
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      name: ${resourceName}-cluster-apps
      namespace: ${templateNamespace}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: templates
  namespace: ${templateNamespace}
spec:
  provider: aws
  interval: 10m
  url: oci://${awsAccountId}.dkr.ecr.${awsRegion}.amazonaws.com/templates
  ref:
    tag: v0.0.3
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: templates
  namespace: ${templateNamespace}
  # labels:
  #   sharding.fluxcd.io/key: $shard
spec:
  type: generic
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      name: templates
      namespace: ${templateNamespace}