apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: ${resourceName}-ocirepo-namespace-apps
  namespace: ${templateNamespace}
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: resource-descriptions/wge/clusters.yaml
  templates:
    - repeat: '{ .clusters[?(@.name=="${clusterName}")].namespaces }'
      content:
        apiVersion: templates.weave.works/v1alpha1
        kind: GitOpsSet
        metadata:
          annotations:
            templates.weave.works/delimiters: "((,))"
          labels:
            app.kubernetes.io/name: gitopsset
            app.kubernetes.io/instance: gitopsset-sample
            app.kubernetes.io/part-of: gitopssets-controller
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/created-by: gitopssets-controller
          name: ${resourceName}-deploy-ns-{{ .Repeat.name }}-apps
          namespace: ${templateNamespace}
        spec:
          serviceAccountName: gitopssets
          generators:
            - gitRepository:
                repositoryRef: flux-system
                files:
                  - path: resource-descriptions/wge/clusters.yaml
          templates:
            - repeat: '{ .clusters[?(@.name=="${clusterName}")].namespaces[?(@.name=="{{ .Repeat.name }}")].apps }'
              content:
                apiVersion: source.toolkit.fluxcd.io/v1beta2
                kind: OCIRepository
                metadata:
                  name: ns-{{ .Repeat.name }}-app-(( .Repeat.name ))
                  namespace: {{ .Repeat.name }}
                spec:
                  interval: 10m
                  url: oci://${awsAccountId}.dkr.ecr.{awsRegion}.amazonaws.com/(( .Repeat.name ))

    - repeat: '{ .clusters[?(@.name=="${clusterName}")].namespaces }'
      content:
        apiVersion: templates.weave.works/v1alpha1
        kind: GitOpsSet
        metadata:
          annotations:
            templates.weave.works/delimiters: "((,))"
          labels:
            app.kubernetes.io/name: gitopsset
            app.kubernetes.io/instance: gitopsset-sample
            app.kubernetes.io/part-of: gitopssets-controller
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/created-by: gitopssets-controller
          name: ${resourceName}-deploy-ns-{{ .Repeat.name }}-apps
          namespace: ${templateNamespace}
        spec:
          serviceAccountName: gitopssets
          generators:
            - gitRepository:
                repositoryRef: flux-system
                files:
                  - path: resource-descriptions/wge/clusters.yaml
          templates:
            - repeat: '{ .clusters[?(@.name=="${clusterName}")].namespaces[?(@.name=="{{ .Repeat.name }}")].apps }'
              content:
                apiVersion: source.toolkit.fluxcd.io/v1beta2
                kind: OCIRepository
                metadata:
                  name: ns-{{ .Repeat.name }}-app-(( .Repeat.name ))
                  namespace: {{ .Repeat.name }}
                spec:
                  interval: 10m
                  url: oci://${awsAccountId}.dkr.ecr.{awsRegion}.amazonaws.com/(( .Repeat.name ))