apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: ${resourceName}-namespaces
  namespace: ${templateNamespace}
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: resource-descriptions/wge/clusters/${clusterName}.yaml
  templates:
    - repeat: '{ .namespaces }'
      content:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: OCIRepository
        metadata:
          name: "ns-{{ .Repeat.name }}"
          namespace: ${templateNamespace}
        spec:
          interval: 10m
          url: "oci://${awsAccountId}.dkr.ecr.${awsRegion}.amazonaws.com/ns-{{ .Repeat.name }}"

    - repeat: '{ .apps }'
      content:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: "ns-{{ .Repeat.name }}"
          namespace: ${templateNamespace}
        spec:
          interval: 1m
          prune: true
          wait: true
          timeout: 5m
          sourceRef:
            kind: OCIRepository
            name: "ns-{{ .Repeat.name }}"
          path: ./
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-config
