---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: global-config
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: ${global_config_branch}
  url: https://github.com/${GITHUB_GLOBAL_CONFIG_ORG}/${GITHUB_GLOBAL_CONFIG_REPO}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-components
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mgmt-cluster/addons/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/${GITHUB_MGMT_ORG}/${GITHUB_MGMT_REPO}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./${target_path}/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

