apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-leaf-config
  namespace: wge
spec:
  dependsOn:
    - name: wge-sa
      namespace: flux-system
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  path: ./leaf-clusters/wge-leaf-config
  prune: true
  timeout: 5m
  wait: true
  postBuild:
    substitute:
      clusterName: ${wge_cluster_name}
      GitHubOrg: ${GITHUB_MGMT_ORG}
      GitHubRepo: ${GITHUB_MGMT_REPO}
      globalGitHubOrg: ${GITHUB_GLOBAL_CONFIG_ORG}
      globalGitHubRepo: ${GITHUB_GLOBAL_CONFIG_REPO}
      globalGitHubBranch: ${global_config_branch}
      awsAccountId: \"${AWS_ACCOUNT_ID}\"
      prefixName: ${PREFIX_NAME}
      awsRegion: ${AWS_REGION}
      awsTagCreator: ${AWS_TAG_creator}
      awsTagCustomer: ${AWS_TAG_customer}
      awsTagProjectGid: \"${AWS_TAG_projectGid}\"
      userEmail: ${USER_EMAIL}
      commitUser: ${GITHUB_USER}
      resourceName: kind
      templateNamespace: wge
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wge-leaf
  namespace: wge
spec:
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  timeout: 5m
  wait: true
  dependsOn:
  - name: wge-leaf-config
  interval: 5m0s
  path: ./leaf-clusters/wge-leaf
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wge-leaf-apps
  namespace: wge
spec:
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  timeout: 5m
  wait: true
  dependsOn:
  - name: wge-leaf
  interval: 5m0s
  path: ./leaf-clusters/wge-leaf-apps
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config