apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: 'leaf-apply-${resourceName}-${clusterName}'
  namespace: ${templateNamespace}
spec:
  interval: 1h
  dependsOn:
    - name: 'eks-config-${resourceName}-${clusterName}'
  retryInterval: 20s
  path: ./terraform/cluster-templates/leaf-apply-${scmType}
  approvePlan: auto
  destroyResourcesOnDeletion: true
  backendConfig:
    customConfiguration: |
      backend "s3" {
        key            = "${mgmtClusterName}/${templateNamespace}/leaf-apply/${resourceName}/${clusterName}/terraform.tfstate"
        bucket         = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
        region         = "${awsRegion}"
        encrypt        = true
        dynamodb_table = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
      }
  vars:
    - name: cluster_name
      value: ${resourceName}-${clusterName}
    - name: resource_name
      value: ${resourceName}
    - name: template_namespace
      value: ${templateNamespace}
    - name: target_path
      value: 'clusters/${templateNamespace}/${resourceName}/${clusterName}'
    - name: cset
      value: ${cset}
    - name: region
      value: ${region}
    - name: env
      value: ${env}
  varsFrom:
    - kind: ConfigMap
      name: leaf-cluster-config
      varsKeys:
        - git_commit_author
        - git_commit_email
        - github_owner
        - github_org
        - repository_name
    - kind: Secret
      name: github-leaf-token
    - kind: Secret
      name: ${resourceName}-${clusterName}-cluster-config
    - kind: ConfigMap
      name: cluster-config
      varsKeys:
        - clusterPrefix
        - globalGitHubOrg
        - globalGitHubRepo
        - globalGitHubBranch
        - awsAccountId
        - prefixName
        - awsRegion
        - awsTagCreator
        - awsTagCustomer
        - awsTagProjectGid
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: ${templateNamespace}
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-creds
