apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana-agent
      version: 0.31.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  values:
    agent:
      mode: flow
      extraPorts:
        - name: faro
          port: 12347
          targetPort: 12347
          protocol: TCP
      configMap:
        create: false
        name: grafana-agent
    crds:
      create: false

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
        nginx.ingress.kubernetes.io/rewrite-target: /
      tls:
      - secretName: faro-tls
        hosts:
          - faro.${dnsSuffix}

      hosts:
      - faro.${dnsSuffix}
      paths:
      - /?(.*)
