apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      version: 0.15.0-rc.5
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
  values:
    allowBreakTheGlass: true
    image:
      # repository: pcarlton/tf-controller
      tag: "v0.15.0-rc.5"
    runner:
      image:
        # repository: pcarlton/tf-runner
        tag: "v0.15.0-rc.5"
      # serviceAccount:
      #   annotations:
      #     eks.amazonaws.com/role-arn: ${tfRunnerRoleArn}
      grpc:
        maxMessageSize: 30
    certRotationCheckFrequency: 3m0s
    certValidityDuration: 5m
    caCertValidityDuration: 10m
