apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ${resourceName}-app-${appName}
  namespace: ${templateNamespace}
spec:
  interval: 10m
  url: oci://${awsAccountId}.dkr.ecr.${awsRegion}.amazonaws.com/${appName}
  ref:
    tag: latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${resourceName}-app-{{ .Repeat.name }}
  namespace: ${templateNamespace}
spec:
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: ${resourceName}-app-${appName}
  path: ./
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
    substitute:
      appName: '{{ .Repeat.name }}'
