apiVersion: v1
kind: Namespace
metadata:
  name: ${appNamespace}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ${appName}
  namespace: ${appNamespace}
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${appName}
  namespace: ${appNamespace}
spec:
  interval: 10m
  chart:
    spec:
      chart: gitopssets-controller
      sourceRef:
        kind: HelmRepository
        name: ${appName}
        namespace: ${appNamespace}
      version: ${appVersion}
