apiVersion: v1
kind: Namespace
metadata:
  name: capa-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: aws
  namespace: capa-system
spec:
  secretName: capi-aws-default
  version: v2.0.3
  deployment:
    containers:
    - args:
        --feature-gates: MachinePool=true,ClusterResourceSet=true,ClusterTopology=true
      name: manager