apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: ${resourceName}-cluster-namespaces
  namespace: ${templateNamespace}
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: resource-descriptions/wge/clusters.yaml
  templates:
    - repeat: '{ .clusters[?(@.name=="${clusterName}")].namespaces }'
      content:
        kind: Kustomization
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        metadata:
          name: namespace-{{ .Repeat.name }}
          annotations:
            templates.weave.works/create-request: ''
        spec:
          interval: 1m0s
          sourceRef:
            kind: GitRepository
            name: flux-system
            namespace: global-config
          path: ./leaf-clusters/namespace
          prune: true
          wait: true
          timeout: 5m
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-config
            substitute:
              nameSpace: '{{ .Repeat.name }}'
              templateNamespace: ${templateNamespace}
              resourceName: ${resourceName}
