apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${resourceName}-oci-src
  namespace: ${templateNamespace}
spec:
  interval: 10m0s
  timeout: 2m
  path: ./leaf-clusters/apps/oci-apps/oci-src
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: ${resourceName}-oci-apps
#   namespace: ${templateNamespace}
# spec:
#   interval: 10m0s
#   timeout: 2m
#   path: ./leaf-clusters/oci-apps
#   prune: true
#   wait: true
#   dependsOn:
#     - name: ${resourceName}-oci-src
#   sourceRef:
#     kind: GitRepository
#     name: global-config
#     namespace: flux-system
#   postBuild:
#     substituteFrom:
#       - kind: ConfigMap
#         name: cluster-config
