apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${resourceName}-apps
  namespace: ${templateNamespace}
spec:
  interval: 1m0s
  path: ./leaf-clusters/apps/templates/generator/cluster-apps
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
    substitute:
      target: namespace
