# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: ${resourceName}-apps
#   namespace: ${templateNamespace}
# spec:
#   interval: 10m0s
#   path: ./leaf-clusters/apps/templates/generator/cluster-apps
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: global-config
#     namespace: flux-system
#   postBuild:
#     substituteFrom:
#       - kind: ConfigMap
#         name: cluster-config
#     substitute:
#       target: namespace
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${resourceName}-oci-apps
  namespace: ${templateNamespace}
spec:
  interval: 10m0s
  path: ./leaf-clusters/oci-apps
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
