apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 7.2.5
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicas: 1
    deploymentStrategy:
      type: Recreate
    grafana.ini:
      analytics:
        enabled: false
        reporting_enabled: false
        check_for_updates: false
        check_for_plugin_updates: false
      users:
        viewers_can_edit: true
      server:
        root_url: "https://grafana.${dnsSuffix}/grafana"
        serve_from_sub_path: true
        enable_gzip: true
    adminPassword: Password123!

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: prometheus
          type: prometheus
          url: http://prometheus-server
          isDefault: false
          basicAuth: false
        - name: loki
          type: loki
          url: http://loki:3100
          isDefault: true
          basicAuth: false
          jsonData:
            maxLines: 1000
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 2000m
        memory: 1024Mi
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
        nginx.ingress.kubernetes.io/rewrite-target: /
      tls:
      - secretName: grafana-tls
        hosts:
          - grafana.${dnsSuffix}

      hosts:
      - grafana.${dnsSuffix}
      paths:
      - /?(.*)
