apiVersion: v1
kind: Namespace
metadata:
  name: gitopssets-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weaveworks-artifacts-charts
  namespace: gitopssets-system
spec:
  interval: 10m
  url: https://artifacts.wge.dev.weave.works/dev/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitopssets-controller
  namespace: gitopssets-system
spec:
  interval: 10m
  chart:
    spec:
      chart: gitopssets-controller
      sourceRef:
        kind: HelmRepository
        name: weaveworks-artifacts-charts
        namespace: gitopssets-system
      version: 0.10.0
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllerManager:
      args:
        # - --health-probe-bind-address=:8081
        # - --metrics-bind-address=127.0.0.1:8080
        # - --leader-elect
        - --enabled-generators=GitRepository,Cluster,List,APIClient,Matrix
      manager:
        image:
          repository: bigkevmcd/gitopssets-controller
          tag: 178bc77
